# Permalinks
#permalink:        pretty

# Theme
theme:            jekyll-theme-minimal

# Setup
title:            "Rakendustarkvara: R"
tagline:          LTMS.00.016
url:              http://rkursus.github.io/
paginate:         1
baseurl:          /2020
author:
  name:           Kaur Lumiste
  url:            
  email:          kaur.lumiste@ut.ee, anne.selart@ut.ee

# Custom vars
version:          1.0.0
github:
  repo:           http://rkursus.github.io/2020

pages_list:       
  Praktikumid: '/praktikumid'
  Projektid: '/projektid'